[package]
name = "apothiki"
version = "0.1.0"
edition = "2021"
description = "Application-centric package explorer for Arch Linux"

[[bin]]
name = "apo"
path = "src/main.rs"

[dependencies]
anyhow = "1"
thiserror = "2"
flate2 = "1"
tar = "0.4"
zstd = "0.13"
serde = { version = "1.0.229", features = ["derive"] }
postcard = { version = "1.1.3", features = ["use-std"] }
quick-xml = "0.41.0"
ratatui = "0.30.2"
crossterm = "0.29.0"
image = { version = "0.25.10", default-features = false, features = ["png"] }
resvg = "0.48.1"
ratatui-image = { version = "11.0.6", default-features = false, features = ["crossterm"] }

[dev-dependencies]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
